name: build-desktop

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Windows
        run: npm run build-win
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: |
            dist/*.exe
            dist/*-portable*.exe
            dist/*.blockmap
            dist/latest*.yml
          if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build macOS
        run: npm run build-mac
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist
          path: |
            dist/*.dmg
            dist/*.zip
          if-no-files-found: warn